Use config instead of bind mount for nginx config
try stopping reverse-proxy only after certbot has finished

diff --git a/.github/workflows/deploy_reverse_proxy.yml b/.github/workflows/deploy_reverse_proxy.yml
--- a/.github/workflows/deploy_reverse_proxy.yml
+++ b/.github/workflows/deploy_reverse_proxy.yml
@@ -1,3 +1,4 @@
+name: Update reverse-proxy nginx config via SSH
 on: 
   push:
     branches:
@@ -23,5 +24,23 @@ jobs:
           port: 22
           script: |
             cd /root/teachme/reverse-proxy
-            docker compose build || exit 1
-            docker compose up -d || exit 1
+            docker compose up -d certbot || exit 1
+            TIMEOUT=30
+            START_TIME=$SECONDS
+            while true; do
+              if docker logs certbot 2>&1 | grep -q "Successfully received certificate"; then
+                echo "Certbot has finished successfully!"
+                break
+              elif docker logs certbot 2>&1 | grep -q "error" || (( $SECONDS - START_TIME > $TIMEOUT )); then
+                echo "Certbot failed or timed out!"
+                docker compose logs certbot # Print Certbot logs for debugging
+                exit 1
+              fi
+              echo "Waiting for certbot to finish..."
+              sleep 3
+            done
+            echo "Certbot has finished successfully!"
+            docker compose stop reverse-proxy || exit 1
+            docker compose up -d reverse-proxy || exit 1
+
+
